name: test_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.1
  lottie: ^3.1.3
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
